use_frameworks!

platform :ios, '8.0'

target 'lay_first_podspec_Example' do
  pod 'lay_first_podspec', :path => '../'

  target 'lay_first_podspec_Tests' do
    inherit! :search_paths

    
  end
end
